
class Square {
    var center Vector
    var size = 2
    var color = Color.new(0, 0, 1, 1)

    def render(ctx CanvasRenderingContext2D) {
        ctx.beginPath
        ctx.rect(
            (center.x - size / 2) as int,
            (center.y - size / 2) as int,
            size * 2,
            size * 2
        )
        ctx.fillStyle = color.toCSS
        ctx.fill
        ctx.closePath
    }
}
